# NOTE: This file was mostly generated by Claude Sonnet 4.5. It is a *non-critical* module used for logging, and has not been thoroughly reviewed.

from loguru import logger
from typing import Any
from pydantic import BaseModel
from api.utilities.settings import get_settings

settings = get_settings()

def log_pydantic_as_tables(run_id: str, label: str, model: BaseModel, level: str = "INFO", max_width: int = 120):
    """
    Log a Pydantic model with each top-level field as a separate table.
    
    Args:
        run_id: Run identifier for context
        label: Description of what's being logged
        model: Pydantic model instance
        level: Log level (INFO, DEBUG, etc.)
        max_width: Maximum width for tables
    """
    with logger.contextualize(run_id=run_id):
        if settings.enable_run_logs:
            logger.log(level, "")
            logger.log(level, "=" * max_width)
            logger.log(level, f"{label}".center(max_width))
            logger.log(level, "=" * max_width)
            logger.log(level, "")
            
            # Get model fields as dict
            model_dict = model.model_dump() if hasattr(model, 'model_dump') else model.dict()
            
            for field_name, field_value in model_dict.items():
                _log_field_as_table(run_id, field_name, field_value, level, max_width)
            
            logger.log(level, "=" * max_width)
            logger.log(level, "")


def _format_value_expanded(value: Any) -> str:
    """
    Format a value by expanding dict/object fields into key=value pairs.
    
    Args:
        value: The value to format
        
    Returns:
        Formatted string like "key1=val1, key2=val2"
    """
    if value is None:
        return "None"
    elif isinstance(value, dict):
        # Format dict as key=value pairs
        parts = [f"{k}={v}" for k, v in value.items()]
        return ", ".join(parts)
    elif isinstance(value, list):
        # For lists, show count and sample
        if not value:
            return "[]"
        elif len(value) <= 3:
            return str(value)
        else:
            return f"[{len(value)} items]"
    elif isinstance(value, (str, int, float, bool)):
        return str(value)
    else:
        # For other objects, convert to string
        return str(value)


def _log_field_as_table(run_id: str, field_name: str, field_value: Any, level: str, max_width: int):
    """Log a single field as a formatted table."""
    with logger.contextualize(run_id=run_id):
        if settings.enable_run_logs:
        # Simple scalar values
            if field_value is None or isinstance(field_value, (str, int, float, bool)):
                logger.log(level, f"┌─ {field_name} " + "─" * (max_width - len(field_name) - 4))
                logger.log(level, f"│  {field_value}")
                logger.log(level, "└" + "─" * (max_width - 1))
                logger.log(level, "")
            
            # Dictionary (nested object)
            elif isinstance(field_value, dict):
                logger.log(level, f"┌─ {field_name} " + "─" * (max_width - len(field_name) - 4))
                logger.log(level, "│")
                
                # Calculate column widths
                if field_value:
                    key_width = max(len(str(k)) for k in field_value.keys()) + 2
                    value_width = max_width - key_width - 7
                    
                    for key, value in field_value.items():
                        value_str = str(value)
                        if len(value_str) > value_width:
                            value_str = value_str[:value_width-3] + "..."
                        logger.log(level, f"│  {str(key):<{key_width}} : {value_str}")
                else:
                    logger.log(level, "│  (empty)")
                
                logger.log(level, "│")
                logger.log(level, "└" + "─" * (max_width - 1))
                logger.log(level, "")
            
            # List of items
            elif isinstance(field_value, list):
                logger.log(level, f"┌─ {field_name} ({len(field_value)} items) " + "─" * (max_width - len(field_name) - len(str(len(field_value))) - 13))
                logger.log(level, "│")
                
                if not field_value:
                    logger.log(level, "│  (empty list)")
                elif isinstance(field_value[0], dict):
                    # Special handling for user_responses, medications, event_sets
                    if field_name == "user_responses":
                        _log_user_responses_table(run_id, field_value, level, max_width)
                    elif field_name == "medications":
                        _log_medications_table(run_id, field_value, level, max_width)
                    elif field_name == "event_sets":
                        _log_event_sets_table(run_id, field_value, level, max_width)
                    else:
                        # Generic list of dicts
                        _log_list_of_dicts_table(run_id, field_value, level, max_width)
                else:
                    # List of simple values
                    for i, item in enumerate(field_value):
                        item_str = str(item)
                        if len(item_str) > max_width - 10:
                            item_str = item_str[:max_width-13] + "..."
                        logger.log(level, f"│  [{i}] {item_str}")
                
                logger.log(level, "│")
                logger.log(level, "└" + "─" * (max_width - 1))
                logger.log(level, "")
            
            else:
                # Fallback for other types
                value_str = str(field_value)
                if len(value_str) > max_width - 6:
                    value_str = value_str[:max_width-9] + "..."
                logger.log(level, f"┌─ {field_name} " + "─" * (max_width - len(field_name) - 4))
                logger.log(level, f"│  {value_str}")
                logger.log(level, "└" + "─" * (max_width - 1))
                logger.log(level, "")


def _log_user_responses_table(run_id: str, items: list[dict], level: str, max_width: int):
    """Log user_responses with rule_id, value_type, and expanded value columns."""
    with logger.contextualize(run_id=run_id):
        if settings.enable_run_logs:
            if not items:
                return
            
            # Calculate column widths
            rule_id_width = max(len("rule_id"), max(len(str(item.get("rule_id", ""))) for item in items)) + 2
            
            # Get value types and max value length
            value_types = []
            max_value_len = 0
            
            for item in items:
                value = item.get("value")
                if value is None:
                    value_types.append("None")
                elif isinstance(value, bool):
                    value_types.append("bool")
                elif isinstance(value, dict):
                    if "min" in value and "max" in value:
                        if "unit" in value:
                            value_types.append("ValueRangeWithUnits")
                        else:
                            value_types.append("ValueRange")
                    elif "values" in value:
                        value_types.append("ValueWeights")
                    elif "state" in value or "city" in value:
                        value_types.append("ValueLocation")
                    elif "system" in value and "code" in value:
                        value_types.append("ValueCoding")
                    elif "start" in value and "end" in value:
                        value_types.append("ValueTimeRange")
                    else:
                        value_types.append("dict")
                else:
                    value_types.append(type(value).__name__)
                
                # Calculate max value length
                value_str = _format_value_expanded(value)
                max_value_len = max(max_value_len, len(value_str))
            
            value_type_width = max(len("value_type"), max(len(vt) for vt in value_types)) + 2
            
            # ✅ CHANGED: Use actual max value length instead of remaining width
            value_width = max_value_len + 2
            
            # Header
            header = f"│  {'rule_id':<{rule_id_width}} │ {'value_type':<{value_type_width}} │ {'value':<{value_width}}"
            separator = f"│  {'─' * rule_id_width}─┼─{'─' * value_type_width}─┼─{'─' * value_width}"
            
            logger.log(level, header)
            logger.log(level, separator)
            
            # Rows
            for item, value_type in zip(items, value_types):
                rule_id = str(item.get("rule_id", ""))
                value = item.get("value")
                
                # Format value as expanded key=value pairs
                value_str = _format_value_expanded(value)
                
                # ✅ No truncation or wrapping
                logger.log(level, f"│  {rule_id:<{rule_id_width}} │ {value_type:<{value_type_width}} │ {value_str}")

def _log_medications_table(run_id: str, items: list[dict], level: str, max_width: int):
    """Log medications with expanded codeable_concept and dosage."""
    if settings.enable_run_logs:
        with logger.contextualize(run_id=run_id):
            if not items:
                return
            
            # Column widths
            system_width = 50
            code_width = 15
            display_width = 40
            dosage_width = max_width - system_width - code_width - display_width - 13
            
            # Header
            header = f"│  {'system':<{system_width}} │ {'code':<{code_width}} │ {'display':<{display_width}} │ {'dosage':<{dosage_width}}"
            separator = f"│  {'─' * system_width}─┼─{'─' * code_width}─┼─{'─' * display_width}─┼─{'─' * dosage_width}"
            
            logger.log(level, header)
            logger.log(level, separator)
            
            # Rows
            for item in items:
                cc = item.get("codeable_concept", {})
                system = str(cc.get("system", ""))[:system_width]
                code = str(cc.get("code", ""))[:code_width]
                display = str(cc.get("display", ""))[:display_width]
                dosage = str(item.get("dosage", ""))[:dosage_width]
                
                logger.log(level, f"│  {system:<{system_width}} │ {code:<{code_width}} │ {display:<{display_width}} │ {dosage:<{dosage_width}}")


def _log_event_sets_table(run_id: str, items: list[dict], level: str, max_width: int):
    """Log event_sets with name, timing details, and entry count."""
    if settings.enable_run_logs:
        with logger.contextualize(run_id=run_id):
            if not items:
                return
            
            # Column widths
            name_width = 25
            timing_width = 50
            entry_width = max_width - name_width - timing_width - 10
            
            # Header
            header = f"│  {'name':<{name_width}} │ {'timing':<{timing_width}} │ {'entries':<{entry_width}}"
            separator = f"│  {'─' * name_width}─┼─{'─' * timing_width}─┼─{'─' * entry_width}"
            
            logger.log(level, header)
            logger.log(level, separator)
            
            # Rows
            for item in items:
                name = str(item.get("name", ""))[:name_width]
                
                # Format timing
                timing = item.get("timing", {})
                timing_str = _format_value_expanded(timing)[:timing_width]
                
                # Format entries
                entries = item.get("entry", [])
                entry_str = f"[{len(entries)} items]"[:entry_width]
                
                logger.log(level, f"│  {name:<{name_width}} │ {timing_str:<{timing_width}} │ {entry_str:<{entry_width}}")


def _log_list_of_dicts_table(run_id: str, items: list[dict], level: str, max_width: int):
    """Log a generic list of dictionaries as a formatted table."""
    if settings.enable_run_logs:
        with logger.contextualize(run_id=run_id):
            if not items:
                return
            
            # Get all unique keys across all items
            all_keys = []
            for item in items:
                for key in item.keys():
                    if key not in all_keys:
                        all_keys.append(key)
            
            # Calculate column widths
            col_widths = {}
            for key in all_keys:
                max_len = len(str(key))
                for item in items:
                    if key in item:
                        val_len = len(str(item[key]))
                        max_len = max(max_len, val_len)
                col_widths[key] = min(max_len + 2, 40)  # Cap at 40 chars
            
            # Adjust widths if total is too large
            total_width = sum(col_widths.values()) + len(all_keys) + 1
            if total_width > max_width - 4:
                scale_factor = (max_width - 4 - len(all_keys) - 1) / sum(col_widths.values())
                col_widths = {k: max(8, int(v * scale_factor)) for k, v in col_widths.items()}
            
            # Header
            header = "│  " + " │ ".join(str(key)[:col_widths[key]].ljust(col_widths[key]) for key in all_keys)
            logger.log(level, header)
            logger.log(level, "│  " + "─┼─".join("─" * col_widths[key] for key in all_keys))
            
            # Rows
            for item in items:
                row_values = []
                for key in all_keys:
                    value = item.get(key, "")
                    
                    # Handle nested dicts/lists
                    if isinstance(value, dict):
                        value_str = _format_value_expanded(value)
                    elif isinstance(value, list):
                        value_str = f"[{len(value)} items]"
                    else:
                        value_str = str(value)
                    
                    # Truncate if needed
                    if len(value_str) > col_widths[key]:
                        value_str = value_str[:col_widths[key]-3] + "..."
                    
                    row_values.append(value_str.ljust(col_widths[key]))
                
                logger.log(level, "│  " + " │ ".join(row_values))