# NOTE: This file was mostly generated by Claude Sonnet 4.5. It is a *non-critical* module used for logging, and has not been thoroughly reviewed.

import sys
import logging
from pathlib import Path
from loguru import logger
from api.utilities.settings import get_settings

settings = get_settings()

class InterceptHandler(logging.Handler):
    def __init__(self, show_fhirsheets_logs: bool = False):
        super().__init__()
        self.show_fhirsheets_logs = show_fhirsheets_logs 
        
    """
    Intercept standard logging messages and redirect them to Loguru
    """
    def emit(self, record):
        if not self.show_fhirsheets_logs and record.name.split(".")[0] == "fhirsheets":
            pass
        else:
            # Get corresponding Loguru level if it exists
            try:
                level = logger.level(record.levelname).name
            except ValueError:
                level = record.levelno

            # Find caller from where originated the logged message
            frame, depth = logging.currentframe(), 2
            while frame.f_code.co_filename == logging.__file__:
                frame = frame.f_back
                depth += 1

            logger.opt(depth=depth, exception=record.exc_info).log(
                level, record.getMessage()
            )


def setup_logging(
    log_level: str = "INFO",
    log_dir: str = "logs",
    log_file: str = "app.log",
    retention: str = "10 days",
    rotation: str = "100 MB",
    json_logs: bool = False,
    enable_console: bool = True,
    show_fhirsheets_logs: bool = False
):
    """
    Configure Loguru logging
    
    Args:
        log_level: Logging level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
        log_dir: Directory for log files
        log_file: Log file name
        retention: How long to keep logs (e.g., "10 days", "1 week")
        rotation: When to rotate logs (e.g., "100 MB", "1 day", "12:00")
        json_logs: Whether to output logs in JSON format
        enable_console: Whether to log to console
    """
    # Create logs directory
    Path(log_dir).mkdir(parents=True, exist_ok=True)
    log_path = Path(log_dir) / log_file
    
    # Remove default handler
    logger.remove()
    # Console handler
    if enable_console:
        logger.add(
            sys.stdout,
            format="<green>{time:YYYY-MM-DD HH:mm:ss.SSS}</green> | "
                   "<level>{level: <8}</level> | "
                   "<cyan>{name}</cyan>:<cyan>{function}</cyan>:<cyan>{line}</cyan> | "
                   "<level>{message}</level>",
            level=log_level,
            colorize=True,
            backtrace=True,
            diagnose=True,
            filter=lambda record: "run_id" not in record["extra"]
        )
    
    # File handler - Standard format
    if not json_logs:
        logger.add(
            log_path,
            format="{time:YYYY-MM-DD HH:mm:ss.SSS} | {level: <8} | {name}:{function}:{line} | {message}",
            level=log_level,
            rotation=rotation,
            retention=retention,
            compression="zip",
            backtrace=True,
            diagnose=True,
            enqueue=True  # Thread-safe
        )
    else:
        # File handler - JSON format
        logger.add(
            log_path,
            format="{message}",
            level=log_level,
            rotation=rotation,
            retention=retention,
            compression="zip",
            serialize=True,  # JSON output
            backtrace=True,
            diagnose=True,
            enqueue=True
        )
    
    # Separate error log
    error_log_path = Path(log_dir) / "error.log"
    logger.add(
        error_log_path,
        format="{time:YYYY-MM-DD HH:mm:ss.SSS} | {level: <8} | {name}:{function}:{line} | {message}",
        level="ERROR",
        rotation=rotation,
        retention=retention,
        compression="zip",
        backtrace=True,
        diagnose=True,
        enqueue=True
    )
    
    intercept_handler = InterceptHandler(show_fhirsheets_logs=show_fhirsheets_logs)
    
    # Intercept standard logging
    logging.basicConfig(handlers=[intercept_handler], level=0, force=True)
    
    # Intercept uvicorn logs
    for _log in ['uvicorn', 'uvicorn.access', 'uvicorn.error', 'fastapi']:
        _logger = logging.getLogger(_log)
        _logger.handlers = [intercept_handler]
    

    return logger



def create_run_logger(
    run_id: str,
    log_dir: str = "logs",
    log_level: str = "INFO",
    rotation: str = "100 MB",
    retention: str = "10 days"
) -> int:
    """
    Create a run-specific log file that only captures logs for a specific run.
    
    Args:
        run_id: Unique identifier for this run
        log_dir: Directory for log files
        log_level: Logging level for this run
        rotation: When to rotate logs
        retention: How long to keep logs
        
    Returns:
        handler_id: ID of the handler (use with logger.remove() to clean up)
        
    Example:
        # Start a run
        run_id = "experiment_2024_01_15"
        handler_id = create_run_logger(run_id)
        
        # Log with run context
        with logger.contextualize(run_id=run_id):
            if settings.enable_run_logs:
                logger.info("Starting run")
                logger.info("Input: data.csv")
                logger.info("Processing...")
                logger.info("Output: results.json")
        
        # Clean up handler when done
        logger.remove(handler_id)
    """
    Path(log_dir).mkdir(parents=True, exist_ok=True)
    run_log_path = Path(log_dir) / f"{run_id}.log"
    
    # Add handler with filter for this specific run_id
    handler_id = logger.add(
        run_log_path,
        format="{message}",
        level=log_level,
        rotation=rotation,
        retention=retention,
        compression="zip",
        filter=lambda record: record["extra"].get("run_id") == run_id,  # Only logs with this run_id
        backtrace=True,
        diagnose=True,
        enqueue=True
    )
    
    return handler_id


def log_resource_definitions(run_id: str, definitions: list, level: str = "INFO"):
    """
    Log ResourceDefinition objects in a readable format.
    """
    with logger.contextualize(run_id=run_id):
        if settings.enable_run_logs:
            logger.log(level, f"ResourceDefinitions ({len(definitions)} total):")
            
            for i, defn in enumerate(definitions, 1):
                # Assuming ResourceDefinition has entityName, resourceType, profiles
                if hasattr(defn, 'entityName'):
                    logger.log(level, f"  [{i}] {defn.entityName}")
                    logger.log(level, f"      Type: {getattr(defn, 'resourceType', 'N/A')}")
                    if hasattr(defn, 'profiles'):
                        logger.log(level, f"      Profiles: {defn.profiles}")
                else:
                    logger.log(level, f"  [{i}] {defn}")

def log_resource_links(run_id: str, links: list, level: str = "INFO"):
    """
    Log ResourceLink objects in a readable format.
    """
    with logger.contextualize(run_id=run_id):
        if settings.enable_run_logs:
            logger.log(level, f"ResourceLinks ({len(links)} total):")
            
            for i, link in enumerate(links, 1):
                # Assuming ResourceLink has originResource, referencePath, destinationResource
                if hasattr(link, 'originResource'):
                    logger.log(level, f"  [{i}] {link.originResource}")
                    logger.log(level, f"      -> {getattr(link, 'destinationResource', 'N/A')}")
                    logger.log(level, f"      via: {getattr(link, 'referencePath', 'N/A')}")
                else:
                    logger.log(level, f"  [{i}] {link}")