# NOTE: Partially generated by Claude Sonnet 4.5.

from sqlalchemy import create_engine, event
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker, Session, scoped_session
from sqlalchemy.pool import StaticPool
from contextlib import contextmanager
from typing import Dict, Generator
import threading
from loguru import logger

Base = declarative_base()

class DatabaseClient:
    """
    Singleton Database Client for SQLAlchemy.
    Ensures only one instance exists across the application.
    """
    _instances: Dict[str, 'DatabaseClient'] = {}
    _lock = threading.Lock()
    
    def __new__(cls, name: str = "default", *args, **kwargs):
        """Ensure only one instance per name exists"""
        if name not in cls._instances:
            with cls._lock:
                if name not in cls._instances:
                    instance = super().__new__(cls)
                    cls._instances[name] = instance
        return cls._instances[name]
    
    def __init__(
        self,
        name: str = "default",
        database_url: str = "sqlite:///./app.db",
        echo: bool = False,
        pool_size: int = 5,
        max_overflow: int = 10,
        pool_pre_ping: bool = True,
        pool_recycle: int = 3600,           # ← ADDED
        **engine_kwargs
    ):
        """
        Initialize database client (only runs once due to Singleton).
        
        Args:
            database_url: Database connection string
            echo: If True, log all SQL statements
            pool_size: Number of connections to maintain
            max_overflow: Max connections beyond pool_size
            pool_pre_ping: Verify connections before using
            **engine_kwargs: Additional engine configuration
        """
        # Only initialize once
        if hasattr(self, '_initialized'):
            return

        self.name = name
        self.database_url = database_url
        self.echo = echo
        self._initialized = True
        
        # Configure engine based on database type
        connect_args = engine_kwargs.pop('connect_args', {})
        
        # SQLite-specific configuration
        if database_url.startswith('sqlite'):
            connect_args.setdefault('check_same_thread', False)
            # For in-memory SQLite, use StaticPool
            if ':memory:' in database_url:
                engine_kwargs['poolclass'] = StaticPool
                engine_kwargs['connect_args'] = connect_args
            else:
                engine_kwargs['connect_args'] = connect_args
        else:
            # PostgreSQL/MySQL configuration
            engine_kwargs['pool_size'] = pool_size
            engine_kwargs['max_overflow'] = max_overflow
            engine_kwargs['pool_pre_ping'] = pool_pre_ping
            engine_kwargs['pool_recycle'] = pool_recycle 
        
        # Create engine
        self.engine = create_engine(
            database_url,
            echo=echo,
            **engine_kwargs
        )
        
        # Enable foreign keys for SQLite
        if database_url.startswith('sqlite'):
            @event.listens_for(self.engine, "connect")
            def set_sqlite_pragma(dbapi_conn, connection_record):
                cursor = dbapi_conn.cursor()
                cursor.execute("PRAGMA foreign_keys=ON")
                cursor.close()
        
        # Create session factory
        self.SessionLocal = sessionmaker(
            autocommit=False,
            autoflush=False,
            bind=self.engine
        )
        
        # Create thread-safe scoped session
        self.ScopedSession = scoped_session(self.SessionLocal)
        
        logger.info(f"Database client '{name}' initialized: {database_url}")
    
    @classmethod
    def get_instance(cls, name: str = "default") -> 'DatabaseClient':
        """Get a named database client instance..."""
        if name not in cls._instances:
            raise RuntimeError(
                f"DatabaseClient '{name}' not initialized. "
                f"Call DatabaseClient(name='{name}', database_url=...) first."
            )
        return cls._instances[name]
    
    @classmethod
    def is_initialized(cls, name: str = "default") -> bool:
        """Check if a named client has been initialized"""
        return name in cls._instances
    
    def get_session(self) -> Session:
        """
        Get a new database session.
        Remember to close it when done!
        
        Usage:
            session = db_client.get_session()
            try:
                # do work
            finally:
                session.close()
        """
        return self.SessionLocal()

    @classmethod
    def get_all_instances(cls) -> Dict[str, 'DatabaseClient']:
        """Get all initialized database clients"""
        return cls._instances.copy()

    @classmethod
    def close_all(cls):
        """Close all database connections"""
        for name, instance in cls._instances.items():
            instance.close()
        logger.info("All database clients closed")

    @contextmanager
    def session_scope(self) -> Generator[Session, None, None]:
        """
        Provide a transactional scope with automatic cleanup.
        
        Usage:
            with db_client.session_scope() as session:
                user = session.query(User).first()
        """
        session = self.SessionLocal()
        try:
            yield session
            session.commit()
        except Exception:
            session.rollback()
            raise
        finally:
            session.close()
    
    def get_scoped_session(self) -> Session:
        """
        Get a thread-local session.
        Useful for web applications where each request is in its own thread.
        
        Usage:
            session = db_client.get_scoped_session()
            # Session is automatically managed per thread
            # Call db_client.remove_scoped_session() at end of request
        """
        return self.ScopedSession()
    
    def remove_scoped_session(self):
        """Remove the current scoped session"""
        self.ScopedSession.remove()
    
    def create_all_tables(self):
        Base.metadata.create_all(bind=self.engine)
        logger.info(f"All tables created for '{self.name}'.")
    
    def drop_all_tables(self):
        Base.metadata.drop_all(bind=self.engine)
        logger.info(f"All tables deleted for '{self.name}'.")
    
    def reset_database(self):
        self.drop_all_tables()
        self.create_all_tables()
        logger.info(f"Database reset complete for '{self.name}'.")
    
    def close(self):
        """Close all connections and dispose of the engine"""
        self.ScopedSession.remove()
        self.engine.dispose()
        logger.info(f"All database connections closed for '{self.name}'.")
    
    def __repr__(self):
        return f"DatabaseClient(name='{self.name}', url='{self.database_url}', echo={self.echo})"


# Dependency for FastAPI
def get_db(db_name: str = "default") -> Generator[Session, None, None]:
    db_client = DatabaseClient.get_instance(db_name)
    session = db_client.get_session()
    try:
        yield session
    finally:
        session.close()

def get_main_db() -> Generator[Session, None, None]:
    """Convenience dependency for app database."""
    yield from get_db("main")

def get_omop_db() -> Generator[Session, None, None]:
    """Convenience dependency for OMOP CDM database."""
    yield from get_db("omop")