# Generated by Claude Sonnet 4.5

# api/seeds.py
import csv
import pandas as pd
from pathlib import Path
from sqlalchemy.orm import Session
from api.database.db_preset_tables import ValuePreset, ValueTypeEnum
from api.database.db_other_tables import TribalAffiliation
from loguru import logger


path_to_seed_data = "./data/lab_value_presets.csv"

# Define which columns map to database fields
DB_COLUMNS = {
    'code',
    'system', 
    'preset_name',
    'value_type',
    'quantity_min',
    'quantity_max',
    'quantity_unit',
    'priority'
}

# Documentation columns that will be ignored
DOC_COLUMNS = {'label', 'notes', 'description', 'comment', 'reference'}

def load_csv(filename: str) -> list[dict]:
    """Load CSV file from data directory"""
    csv_path = Path(__file__).parent.parent.parent / "data" / filename
    
    if not csv_path.exists():
        logger.error(f"CSV file not found: {csv_path}")
        raise FileNotFoundError(f"Required seed data file missing: {filename}")
    
    with open(csv_path, 'r', encoding='utf-8-sig') as f:
        reader = csv.DictReader(f)
        
        # Log which columns are being ignored
        all_columns = set(reader.fieldnames)
        ignored = all_columns - DB_COLUMNS
        if ignored:
            logger.info(f"Ignoring documentation columns: {', '.join(sorted(ignored))}")
        
        # Strip whitespace from all values
        return [
            {k.strip(): v.strip() if v else None for k, v in row.items()}
            for row in reader
        ]

def parse_float_or_none(value: str) -> float | None:
    """Parse float value, return None if empty or invalid"""
    if not value or value == '':
        return None
    try:
        return float(value)
    except (ValueError, TypeError):
        logger.warning(f"Could not parse float: {value}")
        return None

def parse_int_or_default(value: str, default: int = 4) -> int:
    """Parse integer with default fallback"""
    if not value or value == '':
        return default
    try:
        return int(value)
    except (ValueError, TypeError):
        logger.warning(f"Could not parse int: {value}, using default {default}")
        return default

def seed_lab_value_presets(db: Session, force_reseed: bool = False):
    """Seed lab value presets from CSV"""
    
    # Check if data already exists
    existing_count = db.query(ValuePreset).count()
    if existing_count > 0 and not force_reseed:
        logger.info(f"ValuePreset table already has {existing_count} records, skipping seed...")
        return existing_count
    
    # Clear existing data if forcing reseed
    if force_reseed and existing_count > 0:
        logger.warning(f"Force reseed enabled - deleting {existing_count} existing records")
        db.query(ValuePreset).delete()
        db.commit()
    
    # Load CSV data
    rows = load_csv("lab_value_presets.csv")
    
    if not rows:
        logger.warning("No data found in lab_value_presets.csv")
        return 0
    
    presets = []
    errors = []
    
    for idx, row in enumerate(rows, start=2):  # Start at 2 to account for header row
        try:
            # Validate required fields
            if not all([row.get('code'), row.get('system'), row.get('preset_name'), row.get('value_type')]):
                # Include label in error message if available for easier debugging
                label = row.get('label', '')
                errors.append(f"Row {idx} ({label}): Missing required field(s)")
                continue
            
            # Validate value_type enum
            try:
                value_type = ValueTypeEnum(row['value_type'])
            except ValueError:
                label = row.get('label', '')
                errors.append(f"Row {idx} ({label}): Invalid value_type '{row['value_type']}'. Must be 'Quantity' or 'string'")
                continue
            
            # Only use DB columns - ignore documentation columns
            preset = ValuePreset(
                code=row['code'],
                system=row['system'],
                preset_name=row['preset_name'],
                value_type=value_type,
                quantity_min=parse_float_or_none(row.get('quantity_min')),
                quantity_max=parse_float_or_none(row.get('quantity_max')),
                quantity_unit=row.get('quantity_unit') or None,
                priority=parse_int_or_default(row.get('priority'), default=4)
            )
            
            presets.append(preset)
            
        except Exception as e:
            label = row.get('label', '')
            errors.append(f"Row {idx} ({label}): {str(e)}")
            logger.error(f"Error processing row {idx}: {e}")
            logger.error(f"Row data: {row}")
    
    # Report errors
    if errors:
        logger.error(f"Found {len(errors)} errors while processing CSV:")
        for error in errors[:10]:  # Show first 10 errors
            logger.error(f"  - {error}")
        if len(errors) > 10:
            logger.error(f"  ... and {len(errors) - 10} more errors")
    
    # Insert valid records
    if presets:
        try:
            db.add_all(presets)
            db.commit()
            logger.info(f"✓ Successfully seeded {len(presets)} lab value presets")
            return len(presets)
        except Exception as e:
            db.rollback()
            logger.error(f"Database error while seeding: {e}")
            raise
    else:
        logger.warning("No valid presets to seed")
        return 0

def seed_tribal_affiliations(db: Session, force_reseed: bool = False):
    """Seed tribal affiliations from CSV using pandas"""
    
    # Check if data already exists
    existing_count = db.query(TribalAffiliation).count()
    if existing_count > 0 and not force_reseed:
        logger.info(f"tribal_affiliation table already has {existing_count} records, skipping seed...")
        return existing_count
    
    # Clear existing data if forcing reseed
    if force_reseed and existing_count > 0:
        logger.warning(f"Force reseed enabled - deleting {existing_count} existing tribal affiliation records")
        db.query(TribalAffiliation).delete()
        db.commit()
    
    # Load CSV with pandas
    csv_path = Path(__file__).parent.parent.parent / "data" / "tribal_affiliations.csv"
    
    if not csv_path.exists():
        logger.error(f"CSV file not found: {csv_path}")
        raise FileNotFoundError(f"Required seed data file missing: tribal_affiliations.csv")
    
    try:
        # skipinitialspace=True handles spaces after commas in CSV
        df = pd.read_csv(csv_path, skipinitialspace=True)
        
        # Strip whitespace from string columns (map replaces deprecated applymap)
        df = df.map(lambda x: x.strip() if isinstance(x, str) else x)
        
        # Convert to list of dicts for bulk insert
        records = df.to_dict('records')
        
        if not records:
            logger.warning("No data found in tribal_affiliations.csv")
            return 0
        
        # Bulk insert using SQLAlchemy
        db.bulk_insert_mappings(TribalAffiliation, records)
        db.commit()
        
        logger.info(f"✓ Successfully seeded {len(records)} tribal affiliations")
        return len(records)
        
    except Exception as e:
        db.rollback()
        logger.error(f"Error seeding tribal affiliations: {e}")
        raise

from api.database.db_other_tables import Industry, Occupation

def seed_industries(db: Session, force_reseed: bool = False):
    """Seed industries from CSV"""
    existing_count = db.query(Industry).count()
    if existing_count > 0 and not force_reseed:
        logger.info(f"industry table already has {existing_count} records, skipping seed...")
        return existing_count
    
    if force_reseed and existing_count > 0:
        logger.warning(f"Force reseed enabled - deleting {existing_count} existing industry records")
        # Must delete occupations first due to foreign key constraint
        occupation_count = db.query(Occupation).count()
        if occupation_count > 0:
            logger.warning(f"  Deleting {occupation_count} occupation records first (foreign key dependency)")
            db.query(Occupation).delete()
        db.query(Industry).delete()
        db.commit()
    
    csv_path = Path(__file__).parent.parent.parent / "data" / "industries.csv"
    
    if not csv_path.exists():
        logger.error(f"CSV file not found: {csv_path}")
        raise FileNotFoundError(f"Required seed data file missing: industries.csv")
    
    try:
        # Read CSV with explicit dtype to preserve leading zeros in codes
        df = pd.read_csv(csv_path, skipinitialspace=True, dtype={'code': str})
        df = df.map(lambda x: x.strip() if isinstance(x, str) else x)
        records = df.to_dict('records')
        
        if not records:
            logger.warning("No data found in industries.csv")
            return 0
        
        db.bulk_insert_mappings(Industry, records)
        db.commit()
        
        logger.info(f"✓ Successfully seeded {len(records)} industries")
        return len(records)
        
    except Exception as e:
        db.rollback()
        logger.error(f"Error seeding industries: {e}")
        raise

def seed_occupations(db: Session, force_reseed: bool = False):
    """Seed occupations from CSV (requires industries to be seeded first)"""
    existing_count = db.query(Occupation).count()
    if existing_count > 0 and not force_reseed:
        logger.info(f"occupation table already has {existing_count} records, skipping seed...")
        return existing_count
    
    if force_reseed and existing_count > 0:
        logger.warning(f"Force reseed enabled - deleting {existing_count} existing occupation records")
        db.query(Occupation).delete()
        db.commit()
    
    csv_path = Path(__file__).parent.parent.parent / "data" / "occupations.csv"
    
    if not csv_path.exists():
        logger.error(f"CSV file not found: {csv_path}")
        raise FileNotFoundError(f"Required seed data file missing: occupations.csv")
    
    try:
        # Read CSV with explicit dtype to ensure industry_code is string
        df = pd.read_csv(csv_path, skipinitialspace=True, dtype={'industry_code': str, 'code': str})
        df = df.map(lambda x: x.strip() if isinstance(x, str) else x)
        records = df.to_dict('records')
        
        if not records:
            logger.warning("No data found in occupations.csv")
            return 0
        
        # Resolve industry_code to industry_id and filter out unmapped records
        valid_records = []
        for record in records:
            industry_code = str(record['industry_code']).strip()
            industry = db.query(Industry).filter(
                Industry.code == industry_code
            ).first()
            
            if not industry:
                # Debug: show what codes exist
                all_industry_codes = [i.code for i in db.query(Industry.code).all()]
                logger.warning(f"Industry code '{industry_code}' (type: {type(industry_code)}, len: {len(industry_code)}) not found for occupation '{record['display']}'")
                logger.debug(f"Available industry codes include: {all_industry_codes[:10]}")
                continue
            
            record['industry_id'] = industry.industry_id
            del record['industry_code']  # Remove before insert
            valid_records.append(record)
        
        if not valid_records:
            logger.warning("No occupations could be mapped to industries")
            return 0
        
        db.bulk_insert_mappings(Occupation, valid_records)
        db.commit()
        
        logger.info(f"✓ Successfully seeded {len(records)} occupations")
        return len(records)
        
    except Exception as e:
        db.rollback()
        logger.error(f"Error seeding occupations: {e}")
        raise


def seed_all(db: Session, force_reseed: bool = False):
    """Run all seed functions"""
    try:
        seed_lab_value_presets(db, force_reseed=force_reseed)
    except Exception as e:
        db.rollback()
        logger.error(f"Lab value presets seeding failed: {e}")
    
    try:
        seed_tribal_affiliations(db, force_reseed=force_reseed)
    except Exception as e:
        db.rollback()
        logger.error(f"Tribal affiliations seeding failed: {e}")
    
    try:
        seed_industries(db, force_reseed) 
        seed_occupations(db, force_reseed) 
    except Exception as e:
        db.rollback()
        logger.error(f"ODH occupations and industry seeding failed: {e}")

    logger.info("All seeding operations complete")
