# NOTE: THIS FILE WAS GENERATED BY CLAUDE SONNET 4.5 AND IS FOR TYPING ONLY

from typing import Any, Dict, Optional, List, Literal
from pydantic import Field, field_validator, model_serializer, model_validator
from datetime import datetime
from api.models.no_null_camel_model import NoNullCamelModel

# Base/Primitive Types
class Coding(NoNullCamelModel):
    """FHIR Coding data type."""
    
    system: Optional[str] = Field(None, description="Identity of the terminology system")
    version: Optional[str] = Field(None, description="Version of the system")
    code: Optional[str] = Field(None, description="Symbol in syntax defined by the system")
    display: Optional[str] = Field(None, description="Representation defined by the system")
    user_selected: Optional[bool] = Field(None, description="If this coding was chosen directly by the user")
    
    model_config = {"extra": "allow"}


class Meta(NoNullCamelModel):
    """FHIR Meta data type."""
    
    version_id: Optional[str] = Field(None, description="Version specific identifier")
    last_updated: Optional[datetime] = Field(None, description="When the resource version last changed")
    source: Optional[str] = Field(None, description="Identifies where the resource comes from")
    profile: Optional[List[str]] = Field(None, description="Profiles this resource claims to conform to")
    security: Optional[List[Coding]] = Field(None, description="Security Labels applied to this resource")
    tag: Optional[List[Coding]] = Field(None, description="Tags applied to this resource")
    
    model_config = {"extra": "allow"}


class Signature(NoNullCamelModel):
    """FHIR Signature data type."""
    
    type: List[Coding] = Field(..., description="Indication of the reason the entity signed the object(s)")
    when: datetime = Field(..., description="When the signature was created")
    who: str = Field(..., description="Who signed (reference)")
    on_behalf_of: Optional[str] = Field(None, description="The party represented")
    target_format: Optional[str] = Field(None, description="The technical format of the signed resources")
    sig_format: Optional[str] = Field(None, description="The technical format of the signature")
    data: Optional[str] = Field(None, description="The actual signature content (base64 encoded)")
    
    model_config = {"extra": "allow"}


# Bundle Backbone Elements
class BundleLink(NoNullCamelModel):
    """Bundle.link backbone element."""
    
    relation: str = Field(..., description="See http://www.iana.org/assignments/link-relations/link-relations.xhtml")
    url: str = Field(..., description="Reference details for the link")
    
    model_config = {"extra": "allow"}


class BundleEntrySearch(NoNullCamelModel):
    """Bundle.entry.search backbone element."""
    
    mode: Optional[str] = Field(None, description="match | include | outcome")
    score: Optional[float] = Field(None, ge=0.0, le=1.0, description="Search ranking (between 0 and 1)")
    
    model_config = {"extra": "allow"}


class BundleEntryRequest(NoNullCamelModel):
    """Bundle.entry.request backbone element."""
    
    method: str = Field(..., description="GET | HEAD | POST | PUT | DELETE | PATCH")
    url: str = Field(..., description="URL for HTTP equivalent of this entry")
    if_none_match: Optional[str] = Field(None, description="For managing cache currency")
    if_modified_since: Optional[datetime] = Field(None, description="For managing cache currency")
    if_match: Optional[str] = Field(None, description="For managing update contention")
    if_none_exist: Optional[str] = Field(None, description="For conditional creates")
    
    model_config = {"extra": "allow"}


class BundleEntryResponse(NoNullCamelModel):
    """Bundle.entry.response backbone element."""
    
    status: str = Field(..., description="Status response code (text optional)")
    location: Optional[str] = Field(None, description="The location (if the operation returns a location)")
    etag: Optional[str] = Field(None, description="The Etag for the resource (if relevant)")
    last_modified: Optional[datetime] = Field(None, description="Server's date time modified")
    outcome: Optional[Dict[str, Any]] = Field(None, description="OperationOutcome with hints and warnings")
    
    model_config = {"extra": "allow"}


class BundleEntry(NoNullCamelModel):
    """Bundle.entry backbone element."""
    
    link: Optional[List[BundleLink]] = Field(None, description="Links related to this entry")
    full_url: Optional[str] = Field(None, description="URI for resource (Absolute URL server address or URI for UUID/OID)")
    # NOTE: Does not match FHIR Spec. In CohGenT this will never be none - if resource is none then something has gone wrong.
    resource: Dict[str, Any] = Field(description="A resource in the bundle")
    search: Optional[BundleEntrySearch] = Field(None, description="Search related information")
    request: Optional[BundleEntryRequest] = Field(None, description="Additional execution information (transaction/batch/history)")
    response: Optional[BundleEntryResponse] = Field(None, description="Results of execution (transaction/batch/history)")
    
    model_config = {"extra": "allow"}
    
    @field_validator('resource')
    @classmethod
    def validate_resource(cls, v: Optional[Dict[str, Any]]) -> Optional[Dict[str, Any]]:
        """Validate that resource has a resourceType if present."""
        if v is not None and 'resourceType' not in v:
            raise ValueError('resource must contain a resourceType field')
        return v


class Bundle(NoNullCamelModel):
    """
    FHIR Bundle Resource - Version 4.0.1 (R4)
    
    A container for a collection of resources.
    """
    
    resource_type: Literal["Bundle"] = Field("Bundle", description="Resource Type", alias="resourceType")
    
    # Resource metadata
    id: Optional[str] = Field(None, description="Logical id of this artifact")
    meta: Optional[Meta] = Field(None, description="Metadata about the resource")
    implicit_rules: Optional[str] = Field(None, description="A set of rules under which this content was created")
    language: Optional[str] = Field(None, description="Language of the resource content")
    
    # Bundle-specific fields
    identifier: Optional[Dict[str, Any]] = Field(None, description="Persistent identifier for the bundle")
    type: str = Field(..., description="document | message | transaction | transaction-response | batch | batch-response | history | searchset | collection")
    timestamp: Optional[datetime] = Field(None, description="When the bundle was assembled")
    total: Optional[int] = Field(None, ge=0, description="If search, the total number of matches")
    link: Optional[List[BundleLink]] = Field(None, description="Links related to this Bundle")
    entry: Optional[List[BundleEntry]] = Field(None, description="Entry in the bundle - will have a resource or information")
    signature: Optional[Signature] = Field(None, description="Digital Signature")
    
    model_config = {
        "extra": "allow",
        "populate_by_name": True
    }
    
    @field_validator('type')
    @classmethod
    def validate_bundle_type(cls, v: str) -> str:
        """Validate bundle type against common values."""
        valid_types = {
            "document", "message", "transaction", "transaction-response",
            "batch", "batch-response", "history", "searchset", "collection"
        }
        if v not in valid_types:
            # Allow but warn - FHIR is extensible
            pass
        return v
    
    @model_validator(mode='after')
    def validate_bundle_constraints(self) -> 'Bundle':
        """Validate FHIR Bundle constraints."""
        bundle_type = self.type
        total = self.total
        entry = self.entry
        timestamp = self.timestamp
        
        # total only allowed for searchset and history bundles
        if total is not None and bundle_type not in ['searchset', 'history']:
            raise ValueError(f'total is only allowed for searchset and history bundles, not {bundle_type}')
        
        # document bundles must have a timestamp
        if bundle_type == 'document' and timestamp is None:
            raise ValueError('document bundles must have a timestamp')
        
        # document bundles must have at least one entry
        if bundle_type == 'document' and (entry is None or len(entry) == 0):
            raise ValueError('document bundles must have at least one entry')
        
        # document bundles first entry must be a Composition
        if bundle_type == 'document' and entry and len(entry) > 0:
            first_resource = entry[0].resource
            if first_resource and first_resource.get('resourceType') != 'Composition':
                raise ValueError('first entry in a document bundle must be a Composition')
        
        # message bundles must have at least one entry
        if bundle_type == 'message' and (entry is None or len(entry) == 0):
            raise ValueError('message bundles must have at least one entry')
        
        # message bundles first entry must be a MessageHeader
        if bundle_type == 'message' and entry and len(entry) > 0:
            first_resource = entry[0].resource
            if first_resource and first_resource.get('resourceType') != 'MessageHeader':
                raise ValueError('first entry in a message bundle must be a MessageHeader')
        
        return self
    
    def get_resources_by_type(self, resource_type: str) -> List[Dict[str, Any]]:
        """
        Get all resources of a specific type from the bundle.
        
        Args:
            resource_type: The FHIR resource type to filter by
            
        Returns:
            List of resources matching the type
        """
        if self.entry is None:
            return []
        
        resources: List[Dict[str, Any]] = []
        for entry in self.entry:
            if entry.resource and entry.resource.get('resourceType') == resource_type:
                resources.append(entry.resource)
        
        return resources
    
    def get_resource_by_id(self, resource_id: str) -> Optional[Dict[str, Any]]:
        """
        Get a resource by its id from the bundle.
        
        Args:
            resource_id: The resource id to search for
            
        Returns:
            The resource if found, None otherwise
        """
        if self.entry is None:
            return None
        
        for entry in self.entry:
            if entry.resource and entry.resource.get('id') == resource_id:
                return entry.resource
        
        return None
    
    def add_entry(
        self,
        resource: Dict[str, Any],
        full_url: Optional[str] = None,
        search: Optional[BundleEntrySearch] = None,
        request: Optional[BundleEntryRequest] = None,
        response: Optional[BundleEntryResponse] = None
    ) -> 'Bundle':
        """
        Add an entry to the bundle.
        
        Args:
            resource: The FHIR resource to add
            full_url: The full URL for the resource
            search: Search information
            request: Request information
            response: Response information
            
        Returns:
            Self for method chaining
        """
        if self.entry is None:
            self.entry = []
        
        entry = BundleEntry(
            resource=resource,
            full_url=full_url,
            search=search,
            request=request,
            response=response
        )
        
        self.entry.append(entry)
        return self
    
    def get_total_entries(self) -> int:
        """Get the total number of entries in the bundle."""
        return len(self.entry) if self.entry else 0
    
    def to_dict(self, mode: Literal['python', 'json'] = 'python') -> Dict[str, Any]:
        """
        Convert to dictionary with null values excluded.
        
        Args:
            mode: Serialization mode - 'python' for Python objects, 'json' for JSON-compatible types
        """
        return self.model_dump(mode=mode, exclude_none=True, by_alias=True)
    
    def to_json(self, indent: Optional[int] = 2, exclude_none: bool = True) -> str:
        """Convert to JSON string."""
        return self.model_dump_json(indent=indent, exclude_none=exclude_none, by_alias=True)
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'Bundle':
        """Create Bundle from dictionary."""
        return cls.model_validate(data)
    
    @classmethod
    def from_json(cls, json_str: str) -> 'Bundle':
        """Create Bundle from JSON string."""
        return cls.model_validate_json(json_str)