# NOTE: THIS FILE WAS GENERATED BY CLAUDE SONNET 4.5 AND IS FOR TYPING ONLY

from typing import Any, Dict, Optional, List, Literal
from fastapi_camelcase import CamelModel
from pydantic import Field, field_validator, model_validator
from datetime import date, datetime
from api.models.FHIR.element import Element

# Base/Primitive Types
class Coding(CamelModel):
    """FHIR Coding data type."""
    
    system: Optional[str] = Field(None, description="Identity of the terminology system")
    version: Optional[str] = Field(None, description="Version of the system")
    code: Optional[str] = Field(None, description="Symbol in syntax defined by the system")
    display: Optional[str] = Field(None, description="Representation defined by the system")
    user_selected: Optional[bool] = Field(None, description="If this coding was chosen directly by the user")
    
    model_config = {"extra": "allow"}


class CodeableConcept(CamelModel):
    """FHIR CodeableConcept data type."""
    
    coding: Optional[List[Coding]] = Field(None, description="Code defined by a terminology system")
    text: Optional[str] = Field(None, description="Plain text representation of the concept")
    
    model_config = {"extra": "allow"}


class Meta(CamelModel):
    """FHIR Meta data type."""
    
    version_id: Optional[str] = Field(None, description="Version specific identifier")
    last_updated: Optional[datetime] = Field(None, description="When the resource version last changed")
    source: Optional[str] = Field(None, description="Identifies where the resource comes from")
    profile: Optional[List[str]] = Field(None, description="Profiles this resource claims to conform to")
    security: Optional[List[Coding]] = Field(None, description="Security Labels applied to this resource")
    tag: Optional[List[Coding]] = Field(None, description="Tags applied to this resource")
    
    model_config = {"extra": "allow"}


class Reference(CamelModel):
    """FHIR Reference data type."""
    
    reference: Optional[str] = Field(None, description="Literal reference, Relative, internal or absolute URL")
    type: Optional[str] = Field(None, description="Type the reference refers to")
    identifier: Optional['Identifier'] = Field(None, description="Logical reference, when literal reference is not known")
    display: Optional[str] = Field(None, description="Text alternative for the resource")
    
    model_config = {"extra": "allow"}


class Period(CamelModel):
    """FHIR Period data type."""
    
    start: Optional[str] = Field(None, description="Starting time with inclusive boundary")
    end: Optional[str] = Field(None, description="End time with inclusive boundary, if not ongoing")
    
    model_config = {"extra": "allow"}


class Identifier(CamelModel):
    """FHIR Identifier data type."""
    
    use: Optional[str] = Field(None, description="usual | official | temp | secondary | old")
    type: Optional[CodeableConcept] = Field(None, description="Description of identifier")
    system: Optional[str] = Field(None, description="The namespace for the identifier value")
    value: Optional[str] = Field(None, description="The value that is unique")
    period: Optional[Period] = Field(None, description="Time period when id is/was valid for use")
    assigner: Optional[Reference] = Field(None, description="Organization that issued id")
    
    model_config = {"extra": "allow"}


class HumanName(Element):
    """FHIR HumanName data type."""
    
    use: Optional[str] = Field(None, description="usual | official | temp | nickname | anonymous | old | maiden")
    text: Optional[str] = Field(None, description="Text representation of the full name")
    family: Optional[str] = Field(None, description="Family name (often called 'Surname')")
    given: Optional[List[str]] = Field(None, description="Given names (not always 'first'). Includes middle names")
    prefix: Optional[List[str]] = Field(None, description="Parts that come before the name")
    suffix: Optional[List[str]] = Field(None, description="Parts that come after the name")
    period: Optional[Period] = Field(None, description="Time period when name was/is in use")
    
    model_config = {"extra": "allow"}


class ContactPoint(CamelModel):
    """FHIR ContactPoint data type."""
    
    system: Optional[str] = Field(None, description="phone | fax | email | pager | url | sms | other")
    value: Optional[str] = Field(None, description="The actual contact point details")
    use: Optional[str] = Field(None, description="home | work | temp | old | mobile")
    rank: Optional[int] = Field(None, description="Specify preferred order of use (1 = highest)")
    period: Optional[Period] = Field(None, description="Time period when the contact point was/is in use")
    
    model_config = {"extra": "allow"}


class Address(CamelModel):
    """FHIR Address data type."""
    
    use: Optional[str] = Field(None, description="home | work | temp | old | billing")
    type: Optional[str] = Field(None, description="postal | physical | both")
    text: Optional[str] = Field(None, description="Text representation of the address")
    line: Optional[List[str]] = Field(None, description="Street name, number, direction & P.O. Box etc.")
    city: Optional[str] = Field(None, description="Name of city, town etc.")
    district: Optional[str] = Field(None, description="District name (aka county)")
    state: Optional[str] = Field(None, description="Sub-unit of country (abbreviations ok)")
    postal_code: Optional[str] = Field(None, description="Postal code for area")
    country: Optional[str] = Field(None, description="Country (e.g. can be ISO 3166 2 or 3 letter code)")
    period: Optional[Period] = Field(None, description="Time period when address was/is in use")
    
    model_config = {"extra": "allow"}


class Attachment(CamelModel):
    """FHIR Attachment data type."""
    
    content_type: Optional[str] = Field(None, description="Mime type of the content, with charset etc.")
    language: Optional[str] = Field(None, description="Human language of the content (BCP-47)")
    data: Optional[str] = Field(None, description="Data inline, base64ed")
    url: Optional[str] = Field(None, description="Uri where the data can be found")
    size: Optional[int] = Field(None, description="Number of bytes of content (if url provided)")
    hash: Optional[str] = Field(None, description="Hash of the data (sha-1, base64ed)")
    title: Optional[str] = Field(None, description="Label to display in place of the data")
    creation: Optional[str] = Field(None, description="Date attachment was first created")
    
    model_config = {"extra": "allow"}


class Narrative(CamelModel):
    """FHIR Narrative data type."""
    
    status: str = Field(..., description="generated | extensions | additional | empty")
    div: str = Field(..., description="Limited xhtml content")
    
    model_config = {"extra": "allow"}


# Patient Backbone Elements
class PatientContact(CamelModel):
    """Patient.contact backbone element."""
    
    relationship: Optional[List[CodeableConcept]] = Field(None, description="The kind of relationship")
    name: Optional[HumanName] = Field(None, description="A name associated with the contact person")
    telecom: Optional[List[ContactPoint]] = Field(None, description="A contact detail for the person")
    address: Optional[Address] = Field(None, description="Address for the contact person")
    gender: Optional[str] = Field(None, description="male | female | other | unknown")
    organization: Optional[Reference] = Field(None, description="Organization that is associated with the contact")
    period: Optional[Period] = Field(None, description="The period during which this contact person or organization is valid")
    
    model_config = {"extra": "allow"}


class PatientCommunication(CamelModel):
    """Patient.communication backbone element."""
    
    language: CodeableConcept = Field(..., description="The language which can be used to communicate with the patient")
    preferred: Optional[bool] = Field(None, description="Language preference indicator")
    
    model_config = {"extra": "allow"}


class PatientLink(CamelModel):
    """Patient.link backbone element."""
    
    other: Reference = Field(..., description="The other patient or related person resource that the link refers to")
    type: str = Field(..., description="replaced-by | replaces | refer | seealso")
    
    model_config = {"extra": "allow"}


# Main Patient Resource
class Patient(CamelModel):
    """
    FHIR Patient Resource - Version 4.0.1 (R4)
    
    Demographics and other administrative information about an individual or animal 
    receiving care or other health-related services.
    """
    
    resource_type: Literal["Patient"] = Field("Patient", description="Resource Type", alias="resourceType")
    
    # Base Resource Elements
    id: Optional[str] = Field(None, description="Logical id of this artifact")
    meta: Optional[Meta] = Field(None, description="Metadata about the resource")
    implicit_rules: Optional[str] = Field(None, description="A set of rules under which this content was created")
    language: Optional[str] = Field(None, description="Language of the resource content")
    text: Optional[Narrative] = Field(None, description="Text summary of the resource, for human interpretation")
    contained: Optional[List[Dict[str, Any]]] = Field(None, description="Contained, inline Resources")
    extension: Optional[List[Dict[str, Any]]] = Field(None, description="Additional content defined by implementations")
    modifier_extension: Optional[List[Dict[str, Any]]] = Field(None, description="Extensions that cannot be ignored")
    
    # Patient-specific Elements
    identifier: Optional[List[Identifier]] = Field(None, description="An identifier for this patient")
    active: Optional[bool] = Field(None, description="Whether this patient's record is in active use")
    name: Optional[List[HumanName]] = Field(None, description="A name associated with the patient")
    telecom: Optional[List[ContactPoint]] = Field(None, description="A contact detail for the individual")
    gender: Optional[str] = Field(None, description="male | female | other | unknown")
    birth_date: Optional[str | date] = Field(None, description="The date of birth for the individual")
    deceased_boolean: Optional[bool] = Field(None, description="Indicates if the individual is deceased or not")
    deceased_date_time: Optional[str] = Field(None, description="Indicates if the individual is deceased or not")
    address: Optional[List[Address]] = Field(None, description="An address for the individual")
    marital_status: Optional[CodeableConcept] = Field(None, description="Marital (civil) status of a patient")
    multiple_birth_boolean: Optional[bool] = Field(None, description="Whether patient is part of a multiple birth")
    multiple_birth_integer: Optional[int] = Field(None, description="Whether patient is part of a multiple birth")
    photo: Optional[List[Attachment]] = Field(None, description="Image of the patient")
    contact: Optional[List[PatientContact]] = Field(None, description="A contact party (e.g. guardian, partner, friend) for the patient")
    communication: Optional[List[PatientCommunication]] = Field(None, description="A language which may be used to communicate with the patient")
    general_practitioner: Optional[List[Reference]] = Field(None, description="Patient's nominated primary care provider")
    managing_organization: Optional[Reference] = Field(None, description="Organization that is the custodian of the patient record")
    link: Optional[List[PatientLink]] = Field(None, description="Link to another patient resource that concerns the same actual person")
    
    model_config = {
        "extra": "allow",
        "populate_by_name": True,
        "json_encoders": {
            datetime: lambda v: v.isoformat()
        }
    }
    
    @field_validator('gender')
    @classmethod
    def validate_gender(cls, v: Optional[str]) -> Optional[str]:
        """Validate gender against allowed values."""
        if v is not None:
            valid_genders = {"male", "female", "other", "unknown"}
            if v not in valid_genders:
                raise ValueError(f'gender must be one of {valid_genders}')
        return v
    
    @model_validator(mode='after')
    def validate_deceased_choice(self) -> 'Patient':
        """Validate that only one of deceased[x] is set."""
        if self.deceased_boolean is not None and self.deceased_date_time is not None:
            raise ValueError('Only one of deceased_boolean or deceased_date_time can be set')
        return self
    
    @model_validator(mode='after')
    def validate_multiple_birth_choice(self) -> 'Patient':
        """Validate that only one of multipleBirth[x] is set."""
        if self.multiple_birth_boolean is not None and self.multiple_birth_integer is not None:
            raise ValueError('Only one of multiple_birth_boolean or multiple_birth_integer can be set')
        return self
    
    def get_official_name(self) -> Optional[HumanName]:
        """Get the official name if available."""
        if self.name:
            for name in self.name:
                if name.use == "official":
                    return name
            # Return first name if no official name
            return self.name[0] if self.name else None
        return None
    
    def get_primary_identifier(self) -> Optional[Identifier]:
        """Get the primary (official or usual) identifier."""
        if self.identifier:
            # Look for official first
            for ident in self.identifier:
                if ident.use == "official":
                    return ident
            # Then usual
            for ident in self.identifier:
                if ident.use == "usual":
                    return ident
            # Return first identifier
            return self.identifier[0] if self.identifier else None
        return None
    
    def is_deceased(self) -> bool:
        """Check if patient is deceased."""
        return self.deceased_boolean is True or self.deceased_date_time is not None
    
    def get_age(self) -> Optional[int]:
        """Calculate age from birth_date. Returns None if birth_date not set or patient deceased."""
        if not self.birth_date:
            return None
        
        try:
            birth = datetime.strptime(self.birth_date, "%Y-%m-%d").date()
            today = date.today()
            age = today.year - birth.year - ((today.month, today.day) < (birth.month, birth.day))
            return age
        except ValueError:
            return None
    
    def to_dict(self, mode: Literal['python', 'json'] = 'python') -> Dict[str, Any]:
        """
        Convert to dictionary.
        
        Args:
            mode: Serialization mode
        """
        return self.model_dump(mode=mode, exclude_none=True, by_alias=True)
    
    def to_json(self, indent: Optional[int] = 2) -> str:
        """Convert to JSON string."""
        return self.model_dump_json(indent=indent, exclude_none=True, by_alias=True)
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'Patient':
        """Create Patient from dictionary."""
        return cls.model_validate(data)
    
    @classmethod
    def from_json(cls, json_str: str) -> 'Patient':
        """Create Patient from JSON string."""
        return cls.model_validate_json(json_str)